import type { Metadata } from "next";
import "./globals.css"; // Import Tailwind CSS
import "antd/dist/reset.css"; // Import CSS antd

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
